---
- name: Play 1 - Apply common baseline to ALL nodes
  hosts: pi_cluster
  become: true
  roles:
    - role: common
  handlers:
    - name: Reboot host # RENAMED
      listen: reboot_host # RENAMED
      ansible.builtin.reboot: { msg: "Rebooting...", connect_timeout: 5, reboot_timeout: 600, post_reboot_delay: 30, test_command: whoami }
      become: true

- name: Play 2 - Deploy Core Services to the Hub Node
  hosts: core_hub
  become: true
  roles:
    - role: gitea
    - role: minio
    - role: registry
    - role: reverse_proxy
    - role: web_server
    - role: authentik
  handlers:
    - name: Restart Gitea # RENAMED
      listen: restart_gitea # RENAMED
      community.docker.docker_compose_v2: { project_src: "{{ app_config_base_path }}/gitea", state: present, restarted: yes }
      become: true
    - name: Restart MinIO # RENAMED
      listen: restart_minio # RENAMED
      community.docker.docker_compose_v2: { project_src: "{{ app_config_base_path }}/minio", state: present, restarted: yes }
      become: true
    - name: Restart Registry # RENAMED
      listen: restart_registry # RENAMED
      community.docker.docker_compose_v2: { project_src: "{{ app_config_base_path }}/registry", state: present, restarted: yes }
      become: true
    - name: Restart Reverse Proxy # RENAMED
      listen: restart_reverse_proxy # RENAMED
      community.docker.docker_compose_v2: { project_src: "{{ app_config_base_path }}/reverse-proxy", state: present, restarted: yes }
      become: true
    - name: Restart Web Server # RENAMED
      listen: restart_web_server # RENAMED
      community.docker.docker_compose_v2: { project_src: "{{ app_config_base_path }}/web-server", state: present, restarted: yes }
      become: true
    - name: Restart Authentik # RENAMED
      listen: restart_authentik # RENAMED
      community.docker.docker_compose_v2: { project_src: "{{ app_config_base_path }}/authentik", state: present, restarted: yes }
      become: true

- name: Play 3 - Deploy Intelligence Platform to the Intel Node
  hosts: intel_node
  become: true
  roles:
    - role: opencti
  handlers:
    - name: Restart OpenCTI # RENAMED
      listen: restart_opencti # RENAMED
      community.docker.docker_compose_v2: { project_src: "{{ app_config_base_path }}/opencti", state: present, restarted: yes }
      become: true

- name: Play 4 - Deploy Management Services to the Mgmt Node
  hosts: mgmt_node
  become: true
  roles:
    - role: portainer
    - role: pihole
  handlers:
    - name: Restart Portainer # RENAMED
      listen: restart_portainer # RENAMED
      community.docker.docker_compose_v2: { project_src: "{{ app_config_base_path }}/portainer", state: present, restarted: yes }
      become: true
    - name: Restart Pi-hole # RENAMED
      listen: restart_pihole # RENAMED
      community.docker.docker_compose_v2: { project_src: "{{ app_config_base_path }}/pihole", state: present, restarted: yes }
      become: true
